---
# Deletes all cron jobs for UNIX_USER
# Recreates all cron obs
- name: Removes all cron jobs for UNIX_USER
  command: "crontab -r -u {{ UNIX_USER }}"
  ignore_errors: True

- name: Install cron jobs
  block:
    # Admissions
    - cron:
        name: "Admission load"
        minute: 7
        hour: "*/2"
        job: "{{ management_command }} parse_admissions && {{ management_command }} fetch_admissions {{ output }}"
    - cron:
        name: "Fetch_Bed_Status"
        minute: 9
        job: "{{ management_command }} fetch_bed_status {{ output }}"

      # Appointments
    - cron:
        name: "Fetch appointments"
        minute: "30"
        job: "{{ management_command }} fetch_appointments {{ output }}"

      # Covid
    - cron:
        name: "Classify covid followup"
        minute: 12
        job: "{{ management_command }} classify_followup {{ output }}"
    - cron:
        name: "Calculate covid dashboard"
        minute: 12
        job: "{{ management_command }} calculate_covid_dashboard {{ output }}"
    - cron:
        name: "Create covid episodes"
        minute: 5
        hour: "*/2"
        job: "{{ management_command }} create_covid_episodes {{ output }}"
    - cron:
        name: "Generate weekly covid extract"
        minute: 1
        hour: 19
        weekday: 0 # Sunday
        job: "{{ management_command }} generate_weekly_covid_extract {{ output }}"
    - cron:
        name: Pre load Covid 19
        minute: 53
        job: "{{ management_command }} pre_load_covid19 {{ output }}"

    # Discharge
    # - cron:
      #   name: "Fetch dischargesummaries"
      #   minute: 35
      #   hour: */12
      #   job: "{{ management_command }} fetch_dischargesummaries {{ output }}"

    # Lab tests
    - cron:
        name: Batch load
        minute: 14
        hour: "*/2"
        job: "{{ management_command }} batch_load2 {{ output }}"
    - cron:
        name: Create observation histories
        minute: 56
        hour: "*/2"
        job: "{{ management_command }} create_observation_histories {{ output }}"

    # ICU
    - cron:
        name: Hard refresh icu current
        minute: 35
        hour: 5
        job: "{{ management_command }} hard_refresh_icu_current {{ output }}"
    - cron:
        name: Load icu handover patients
        minute: 4,9,14,19,24,29,34,39,44,49,54,59
        job: "{{ management_command }} load_icu_handover_patients {{ output }}"

    # Imaging
    - cron:
        name: Fetch imaging
        minute: 17,47
        job: "{{ management_command }} fetch_imaging {{ output }}"

    # Intrahospital api
    - cron:
        name: Feed alert email
        minute: 0
        hour: 12
        weekday: 1,2,3,4,5
        job: "{{ management_command }} feed_alert_email {{ output }}"
    - cron:
        name: Write upstream results
        minute: 29
        job: "{{ management_command }} write_upstream_results {{ output }}"

    # Handover
    - cron:
        name: "Calculate AMT dashboard"
        minute: 45
        hour: 7
        job: "{{ management_command }} calculate_amt_dashboard {{ output }}"
    - cron:
        name: "Sync amt handover"
        minute: 30
        hour: 7,12,20
        job: "{{ management_command }} sync_amt_handover {{ output }}"

    # Demographics
    - cron:
        name: Sync demographics
        minute: 8
        job: "{{ management_command }} sync_demographics {{ output }}"

    # TB
    - cron:
        name: TB patient load
        minute: 0
        hour: 2
        job: "{{ management_command }} tb_patient_load {{ output }}"
    - cron:
        name: TB refresh future appointments
        minute: 12
        hour: 3
        job: "{{ management_command }} tb_refresh_future_appointments {{ output }}"
    # Run every Tuesday every 15 mins in the clinic
    - cron:
        name: TB refresh future appointments
        minute: 5,20,35,50 12,13,14,15,16,17,18
        weekday: 2
        job: "{{ management_command }} tb_refresh_future_appointments {{ output }}"
    - cron:
        name: Create TB observations
        minute: 29
        job: "{{ management_command }} create_tb_observations {{ output }}"

    # Back ups, TBD
    # - cron:
      #   name: Create backups
      #   minute: 0
      #   hour: 3
      #   job: "{{ management_command }} get_backup_size {{ output }}"
    - cron:
        name: Get backup size
        minute: 36
        hour: 7
        job: "{{ management_command }} get_backup_size {{ output }}"

    # System
    - cron:
        name: Check disk space
        minute: 26
        job: "{{ management_command }} check_disk_space {{ output }}"
  vars:
    management_command: "{{ VIRTUALENV_PATH }}/bin/python {{ PROJECT_DIR }}/manage.py }}"
    output: ">> {{ LOG_DIR }}/cron.log 2>&1"
    user: "{{ UNIX_USER }}"
