# Generated by Django 2.0.13 on 2024-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0004_auto_20210930_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opatrecord',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hospital Admission Date'),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='discharge_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hospital Discharge Date'),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='supply',
            field=models.CharField(blank=True, choices=[('RFH', 'RFH'), ('RNOH', 'RNOH'), ('GP', 'GP'), ('Local hospital', 'Local hospital'), ('Private', 'Private')], max_length=200, null=True),
        ),
    ]
