# Generated by Django 2.0.13 on 2024-05-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0005_auto_20240510_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opatrecord',
            name='outcome_early',
        ),
        migrations.RemoveField(
            model_name='opatrecord',
            name='outcome_early_date',
        ),
        migrations.RemoveField(
            model_name='opatrecord',
            name='outcome_two_years',
        ),
        migrations.RemoveField(
            model_name='opatrecord',
            name='outcome_two_years_date',
        ),
    ]
