# Generated by Django 2.0.13 on 2024-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0006_auto_20240514_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatrecord',
            name='complications',
            field=models.CharField(blank=True, choices=[('Allergy', 'Allergy'), ('Liver impairment', 'Liver impairment'), ('Renal impairment', 'Renal impairment'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='opatrecord',
            name='treatment_outcome',
            field=models.CharField(blank=True, choices=[('Cured', 'Cured'), ('Improved', 'Improved'), ('Moved to palliative', 'Moved to palliative')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='opatrecord',
            name='outcome_one_year',
            field=models.CharField(blank=True, choices=[('Achieved treatment aim (uncomplicated)', 'Achieved treatment aim (uncomplicated)'), ('Treatment aim attained (complicated)', 'Treatment aim attained (complicated)'), ('Treatment aim not attained', 'Treatment aim not attained'), ('Indeterminate', 'Indeterminate'), ('Died (non OPAT related)', 'Died (non OPAT related)'), ('Died (OPAT related)', 'Died (OPAT related)'), ('Readmitted', 'Readmitted'), ('Transfer to another provider', 'Transfer to another provider')], max_length=200, null=True),
        ),
    ]
