# Generated by Django 2.0.13 on 2024-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opat', '0007_auto_20240514_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='opatrecord',
            name='microbiology',
            field=models.TextField(blank=True, null=True, verbose_name='Significant Microbiology Results'),
        ),
    ]
