stages:
   - app_test
   - deployment_tests
jobs:
   include:
      - stage: app_test
        language: python
        python:
          - "3.4"
        install:
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - pip install coveralls
          - gem install coveralls-lcov
          - npm install karma karma-coverage jasmine-core karma-jasmine karma-firefox-launcher karma-coveralls

        before_script:
          - export DISPLAY=:99.0
          - sh -e /etc/init.d/xvfb start
        script:
          - opal test --coverage
        after_success:
          - find coverage
          - coveralls-lcov -v -n coverage/Firefox\ 56.0.0\ \(Linux\ 0.0.0\)/lcov.info > coverage/coverage.json
          - cat coverage/coverage.json
          - coveralls debug --merge=coverage/coverage.json
          - coveralls --merge=coverage/coverage.json
        notificatios:
          slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp
      - stage: deployment_tests
        language: python
        python:
          - "2.7"
        install:
          - pip install --upgrade pip
          - pip install -r requirements-deployment.txt
        script:
          - pytest -q deployment_tests/fabric_tests.py
        notifications:
          slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp

