---
# Deploys the current branch to a virtual env
# sets up local settings and runs
# migrate/load_lookup_lists/create_singletons
- name: Creates directories
  become: true
  file:
    path: "{{ PROJECT_PATH }}"
    state: directory
    mode: 0777

- name: Ensure the project directory does not exist
  file:
    state: absent
    path: "{{ PROJECT_DIR }}/"

- name: Deploy our branch
  git: repo={{ GIT_REPO }}
       version={{ GIT_BRANCH }}
       dest={{ PROJECT_DIR }}/
       accept_hostkey=yes
       force=yes

- name: Create the conf directoris
  become: true
  file:
    path: "{{ CONF_DIR }}"
    state: directory
    mode: 0777

- name: Create local settings
  template:
    src: "templates/local_settings.py.jinja2"
    dest: "{{ PROJECT_DIR }}/elcid/local_settings.py"
    mode: 0744
    owner: {{ UNIX_USER }}

- name: Ensure no existing virtualenv exists
  file:
    state: absent
    path: "{{ VIRTUALENV_PATH }}/"

- name: Create the virtualenv
  become: yes
  become_user: ohc
  shell: . /usr/share/virtualenvwrapper/virtualenvwrapper.sh && mkvirtualenv -p /usr/bin/python3 {{ ENV_NAME }}
  args:
    executable: /bin/bash

- name: Set the virtualenv project
  template:
    src: templates/project.jinja2
    dest: "{{ VIRTUALENV_PATH }}/.project"
    mode: 0744
    owner: ohc

- name: Install packages required by the Django app inside virtualenv
  pip:
    virtualenv: "{{ VIRTUALENV_PATH }}"
    requirements: "{{ PROJECT_DIR }}/requirements.txt"

- name: Run Django database migrations
  args:
    chdir: "{{ PROJECT_DIR}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py migrate"

- name: Run Django collectstatic
  args:
    chdir: "{{ PROJECT_DIR}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py collectstatic --noinput"

- name: Make sure the static directory is readable
  become: true
  file:
    path: "{{ PROJECT_PATH }}/static"
    state: directory
    mode: 0711

- name: Create singletons
  args:
    chdir: "{{ PROJECT_DIR}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py create_singletons"

- name: Load lookuplists
  args:
    chdir: "{{ PROJECT_DIR}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py load_lookup_lists"
