---
- name: Things you want on servers generally
  become: true
  user: "{{ UNIX_USER }}"
  hosts: webserver
  gather_facts: no
  roles:
    - setup_server

- name: Make the server capable of running a standard database
  become: true
  user: "{{ UNIX_USER }}"
  hosts: webserver
  gather_facts: yes
  roles:
    - setup_db

- name: Set up the directories for logs, backups etc
  become: true
  user: "{{ UNIX_USER }}"
  hosts: webserver
  gather_facts: yes
  roles:
    - setup_rfh

- name: Deploy the branch to RFH, install requirements
  user: "{{ UNIX_USER }}"
  hosts: webserver
  gather_facts: yes
  roles:
    - deploy_rfh
