# Generated by Django 2.0.13 on 2024-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0061_patientconsultation_reason_for_mdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='discussion',
            field=models.TextField(blank=True, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='patientconsultation',
            name='reason_for_mdt',
            field=models.TextField(blank=True, choices=[('New microbiology result', 'New microbiology result'), ('Infection control', 'Infection control'), ('Clinical management', 'Clinical management'), ('Other', 'Other')], null=True, verbose_name='Reason For MDT'),
        ),
    ]
