# Generated by Django 2.0.13 on 2024-10-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0062_auto_20241001_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='reason_for_mdt',
        ),
    ]
