# Generated by Django 2.0.13 on 2024-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0063_remove_patientconsultation_reason_for_mdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='mdt_ipc',
            field=models.BooleanField(default=False, verbose_name='Infection control'),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='mdt_managemnt',
            field=models.BooleanField(default=False, verbose_name='Clinical management'),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='mdt_new_result',
            field=models.BooleanField(default=False, verbose_name='New microbiology result'),
        ),
        migrations.AddField(
            model_name='patientconsultation',
            name='mdt_other',
            field=models.BooleanField(default=False, verbose_name='Other'),
        ),
    ]
