# Generated by Django 2.0.13 on 2024-10-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0064_auto_20241001_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientconsultation',
            old_name='mdt_managemnt',
            new_name='mdt_management',
        ),
    ]
