# Generated by Django 2.0.13 on 2024-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elcid', '0071_merge_20230911_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineInsertedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='lineinsertedby',
            unique_together={('code', 'system')},
        ),
    ]
