---
# This playbook sets up the directory we will deploy to and makes sure
# we have a log directory, a backups directory and conf directory
- name: Creates directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ PROJECT_PATH }}"
    - "{{ LOG_DIR }}"
    - "{{ BACKUPS_DIR }}"
    - "{{ CONF_DIR }}"


# otherwise it complains silently and
# blows up the world
- name: Creates gunicorn log
  file:
    path: "{{ LOG_DIR }}/gunicorn.log"
    state: touch

- name: Creates directories
  become: true
  file:
    path: "{{ CONF_DIR }}/circus"
    state: directory
