---
# This playbook sets up the directory we will deploy to and makes sure
# we have a log directory and a backups directory
- name: Creates directories
  become: true
  file:
    path: "{{ directory }}"
    state: directory
    mode: 0777
  vars:
    directory:
    - "{{ PROJECT_PATH }}"
    - "{{ LOG_DIR }}"
    - "{{ BACKUPS_DIR }}"
